-- MySQL Script generated by MySQL Workbench
-- Sat Dec 17 09:06:42 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ShareMyTrip
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ShareMyTrip
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ShareMyTrip` DEFAULT CHARACTER SET utf8 ;
USE `ShareMyTrip` ;

-- -----------------------------------------------------
-- Table `ShareMyTrip`.`trips`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShareMyTrip`.`trips` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShareMyTrip`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShareMyTrip`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `picture` BLOB NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShareMyTrip`.`trips_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShareMyTrip`.`trips_users` (
  `trip_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  INDEX `fk_Trips_has_Users_Users1_idx` (`user_id` ASC),
  INDEX `fk_Trips_has_Users_Trips_idx` (`trip_id` ASC),
  CONSTRAINT `fk_Trips_has_Users_Trips`
    FOREIGN KEY (`trip_id`)
    REFERENCES `ShareMyTrip`.`trips` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trips_has_Users_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ShareMyTrip`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShareMyTrip`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShareMyTrip`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShareMyTrip`.`actions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShareMyTrip`.`actions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `company` VARCHAR(45) NULL,
  `reservation` VARCHAR(45) NULL,
  `notes` LONGTEXT NULL,
  `trip_id` INT NOT NULL,
  `price` DECIMAL(5,2) NULL,
  `currency` VARCHAR(3) NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lodgings_Trips1_idx` (`trip_id` ASC),
  INDEX `fk_actions_action_categories1_idx` (`category_id` ASC),
  CONSTRAINT `fk_lodgings_Trips1`
    FOREIGN KEY (`trip_id`)
    REFERENCES `ShareMyTrip`.`trips` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actions_action_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `ShareMyTrip`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShareMyTrip`.`departures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShareMyTrip`.`departures` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `longitude` DECIMAL(9,6) NOT NULL,
  `latitude` DECIMAL(9,6) NOT NULL,
  `date` DATETIME NOT NULL,
  `action_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_position_lodgings1_idx` (`action_id` ASC),
  CONSTRAINT `fk_position_lodgings1`
    FOREIGN KEY (`action_id`)
    REFERENCES `ShareMyTrip`.`actions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShareMyTrip`.`arrivals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShareMyTrip`.`arrivals` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `longitude` DECIMAL(9,6) NOT NULL,
  `latitude` DECIMAL(9,6) NOT NULL,
  `date` DATETIME NOT NULL,
  `action_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_position_lodgings10_idx` (`action_id` ASC),
  CONSTRAINT `fk_position_lodgings10`
    FOREIGN KEY (`action_id`)
    REFERENCES `ShareMyTrip`.`actions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShareMyTrip`.`types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShareMyTrip`.`types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_types_action_categories1_idx` (`category_id` ASC),
  CONSTRAINT `fk_types_action_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `ShareMyTrip`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShareMyTrip`.`participations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShareMyTrip`.`participations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `action_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Prices_Users_Users1_idx` (`user_id` ASC),
  INDEX `fk_actions_users_actions1_idx` (`action_id` ASC),
  CONSTRAINT `fk_Prices_Users_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ShareMyTrip`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actions_users_actions1`
    FOREIGN KEY (`action_id`)
    REFERENCES `ShareMyTrip`.`actions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShareMyTrip`.`methods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShareMyTrip`.`methods` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShareMyTrip`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShareMyTrip`.`payments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(5,2) NOT NULL,
  `currency` VARCHAR(3) NULL,
  `action_id` INT NOT NULL,
  `date` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  `method_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_payments_actions1_idx` (`action_id` ASC),
  INDEX `fk_payments_users1_idx` (`user_id` ASC),
  INDEX `fk_payments_methods1_idx` (`method_id` ASC),
  CONSTRAINT `fk_payments_actions1`
    FOREIGN KEY (`action_id`)
    REFERENCES `ShareMyTrip`.`actions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payments_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ShareMyTrip`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payments_methods1`
    FOREIGN KEY (`method_id`)
    REFERENCES `ShareMyTrip`.`methods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
